/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "passlong.h"

#if ( (TC_IMPL_TC_passlong_0 == 'p') \
&& (TC_IMPL_TC_passlong_1 == 'a') \
&& (TC_IMPL_TC_passlong_2 == 's') \
&& (TC_IMPL_TC_passlong_3 == 's') \
&& (TC_IMPL_TC_passlong_4 == 'l') \
&& (TC_IMPL_TC_passlong_5 == 'o') \
&& (TC_IMPL_TC_passlong_6 == 'n') \
&& (TC_IMPL_TC_passlong_7 == 'g') \
) && !defined(TC_DEF_TC_passlong)
#define TC_DEF_TC_passlong 1
const struct CORBA_TypeCode_struct TC_passlong_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "passlong", "IDL:passlong:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long passlong__classid = 0;
