/*
 * SyrupApplet.java
 *
 * Created on March 5, 2001, 3:25 PM
 */

// Import Syrup classes
import Syrup.*;

// All CORBA applications need these classes.
import org.omg.CORBA.*;

//for the name service...
import org.omg.CosNaming.*;

// The package containing special exceptions thrown by the name service.
import org.omg.CosNaming.NamingContextPackage.*;

import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.applet.*;


/**
 *
 * @author  Brian S. Corbin 
 * @version 
 */
public class SyrupApplet extends javax.swing.JApplet {

  private SyrupManager manager;
  private SyrupClient  client;
  private String       userid  = "default_user";
  private boolean      loggedIn = false; 

    /** Creates new form SyrupApplet */
    public SyrupApplet() {
        initComponents ();
    }

    //use the init() method to initialize CORBA "stuff"
    public void init() {

      try{

        // Create and initialize the ORB 
        // The applet 'this' is passed to make parameters from the <APPLET...> tag
        // available to initialize the ORB
        ORB orb = ORB.init(this, null);
      
        // Get the root naming context
        org.omg.CORBA.Object objRef = orb.resolve_initial_references("NameService");
        NamingContext ncRef = NamingContextHelper.narrow(objRef);

        // Resolve the object reference in naming
        NameComponent nc = new NameComponent("SyrupManager", "CORBin_ML");
        NameComponent path[] = {nc};

        manager = SyrupManagerHelper.narrow(ncRef.resolve(path));

	client = new SyrupClientServant(this,messagesFromUsersArea,syrupUsersBox );
	orb.connect(client);
	

      } catch(Exception e) {
          System.out.println("SyrupApplet exception: " + e);
          e.printStackTrace(System.out);
      }  


    }

    public void destroy() {

	if(loggedIn == true) {
	
		//log out if we are destroyed
		manager.Logout(userid);

	}

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        syrupTabbedPane = new javax.swing.JTabbedPane();
        connectStatusPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        syrupScreenName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        messagePanel = new javax.swing.JPanel();
        postMessageArea = new javax.swing.JTextArea();
	sp0 = new  JScrollPane(postMessageArea);
        postMessageButton = new javax.swing.JButton();
        chatPanel = new javax.swing.JPanel();
        syrupUsersBox = new javax.swing.JComboBox();
	syrupUsersBox.setEditable(false);
	sp1 = new  JScrollPane(syrupUsersBox);
        messagesFromUsersArea = new javax.swing.JTextArea();
	sp2 = new  JScrollPane(messagesFromUsersArea);
        messagesToUserArea = new javax.swing.JTextArea();
	sp3 = new  JScrollPane(messagesToUserArea);
        sendMessageToUserButton = new javax.swing.JButton();
        aboutPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        getContentPane().setLayout(null);
        
        
        connectStatusPanel.setLayout(null);
          
          loginButton.setText("SyrupManager Login");
            loginButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    loginButtonActionPerformed(evt);
                }
            }
            );
            connectStatusPanel.add(loginButton);
            loginButton.setBounds(90, 180, 180, 40);
            
            
          logoutButton.setText("SyrupManager Logout");
            logoutButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    logoutButtonActionPerformed(evt);
                }
            }
            );
            connectStatusPanel.add(logoutButton);
            logoutButton.setBounds(270, 180, 190, 40);
            
            
          connectStatusPanel.add(syrupScreenName);
            syrupScreenName.setBounds(270, 100, 190, 30);
            
            
          jLabel8.setText("Syrup Screen Name: ");
            jLabel8.setFont(new java.awt.Font ("Comic Sans MS", 3, 14));
            connectStatusPanel.add(jLabel8);
            jLabel8.setBounds(80, 90, 250, 50);
            
            
          jLabel9.setText("Welcome to S.Y.R.U.P.!");
            jLabel9.setFont(new java.awt.Font ("Comic Sans MS", 1, 24));
            connectStatusPanel.add(jLabel9);
            jLabel9.setBounds(130, 10, 310, 80);
            
            syrupTabbedPane.addTab("Login/Logout", connectStatusPanel);
          
          
        messagePanel.setLayout(null);
          messagePanel.setName("Syrup");
          
          postMessageArea.setBorder(new javax.swing.border.TitledBorder("Message to Post Via SyrupManager"));
            //messagePanel.add(postMessageArea);
            //postMessageArea.setBounds(50, 20, 480, 140);
	    sp0.setPreferredSize(new Dimension(430,120));
            sp0.setBounds(50, 20, 480, 140);
            messagePanel.add(sp0);
            
            
          postMessageButton.setToolTipText("Click here to post your message!");
            postMessageButton.setText("Post Message to SyrupManager");
            postMessageButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    postMessageButtonActionPerformed(evt);
                }
            }
            );
            messagePanel.add(postMessageButton);
            postMessageButton.setBounds(140, 180, 260, 30);
            
            syrupTabbedPane.addTab("Post a Message", messagePanel);
          
          
        chatPanel.setLayout(null);
          
          syrupUsersBox.setBorder(new javax.swing.border.TitledBorder("Syrup Users Online:"));
            syrupUsersBox.setFont(new java.awt.Font ("Comic Sans MS", 2, 10));
	    //sp1.setPreferredSize(new Dimension(170,100));
            chatPanel.add(sp1);
            sp1.setBounds(350, 20, 180, 120);
            
            
          messagesFromUsersArea.setBorder(new javax.swing.border.TitledBorder("Messages from Syrup Users:"));
	    sp2.setPreferredSize(new Dimension(280,80));
            chatPanel.add(sp2);
            sp2.setBounds(20, 20, 300, 100);
            
            
          messagesToUserArea.setBorder(new javax.swing.border.TitledBorder("Message to send:"));
	    sp3.setPreferredSize(new Dimension(280,40));
            chatPanel.add(sp3);
            sp3.setBounds(20, 140, 300, 100);
            
            
          sendMessageToUserButton.setToolTipText("Click this button to send a message to the selected Syrup User");
            sendMessageToUserButton.setText("Send Message");
            sendMessageToUserButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    sendMessageToUserButtonActionPerformed(evt);
                }
            }
            );
            chatPanel.add(sendMessageToUserButton);
            sendMessageToUserButton.setBounds(340, 180, 190, 40);
            
            syrupTabbedPane.addTab("Chat", chatPanel);
          
          
        aboutPanel.setLayout(null);
          
          jLabel13.setText("Author:  Brian S. Corbin");
            jLabel13.setForeground(java.awt.Color.black);
            jLabel13.setFont(new java.awt.Font ("Lucida Console", 0, 18));
            aboutPanel.add(jLabel13);
            jLabel13.setBounds(100, 40, 370, 30);
            
            
          jLabel16.setText("http://www.corbinator.com");
            jLabel16.setForeground(java.awt.Color.black);
            jLabel16.setFont(new java.awt.Font ("Lucida Console", 0, 18));
            aboutPanel.add(jLabel16);
            jLabel16.setBounds(100, 60, 350, 40);
            
            
          jLabel17.setText("Email: brian@corbinator.com");
            jLabel17.setForeground(java.awt.Color.black);
            jLabel17.setFont(new java.awt.Font ("Lucida Console", 0, 18));
            aboutPanel.add(jLabel17);
            jLabel17.setBounds(100, 90, 350, 40);
            
            syrupTabbedPane.addTab("About Syrup", aboutPanel);
          
          
        getContentPane().add(syrupTabbedPane);
        syrupTabbedPane.setBounds(30, 40, 590, 290);
        
        
        jLabel7.setText("S.Y.R.U.P: Simple Yet Reliable Utility for Product planning");
        jLabel7.setFont(new java.awt.Font ("Comic Sans MS", 0, 14));
        
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 0, 510, 40);
        
        
        jLabel10.setText("SYRUP Status: ");
        jLabel10.setFont(new java.awt.Font ("Comic Sans MS", 1, 14));
        
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 350, 160, 30);
        
        
        statusLabel.setText("Not Connected");
        statusLabel.setForeground(java.awt.Color.red);
        
        getContentPane().add(statusLabel);
        statusLabel.setBounds(140, 350, 170, 30);


	messagesFromUsersArea.setEditable(false);
        
    }//GEN-END:initComponents

  private void sendMessageToUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageToUserButtonActionPerformed
	//Send Message to another User

      if (loggedIn == true) {

		//send message to selected user
		manager.SendMessage(userid,
			     (String)syrupUsersBox.getSelectedItem(), 
			     messagesToUserArea.getText()); 	

		messagesFromUsersArea.append("You told " +
			     (String)syrupUsersBox.getSelectedItem() +
			     ":\n" +
			     messagesToUserArea.getText()); 	
		             
				

		messagesToUserArea.setText("");

      }
      else {

	  JOptionPane.showMessageDialog(this, 
		"You can't chat unless you login!",
		"Please Login!",
		JOptionPane.PLAIN_MESSAGE); 

      }


  }//GEN-LAST:event_sendMessageToUserButtonActionPerformed

  private void postMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postMessageButtonActionPerformed
	//Post Message to SyrupMessage Board
      
      if (loggedIn == true) {
	if((postMessageArea.getText()).equals("")) {
			JOptionPane.showMessageDialog(this, 
				"Please enter a message",
				"Enter a Message to be Posted!",
				JOptionPane.PLAIN_MESSAGE); 
	} 
        else {
		
		//Invoke SyrupManager's PostMessage Operation
		manager.PostMessage(userid, postMessageArea.getText());
		JOptionPane.showMessageDialog(this, 
			"Your message has been posted to the message board.",
			"Message Posted!",
			JOptionPane.PLAIN_MESSAGE); 

	}
      }
      else {
		JOptionPane.showMessageDialog(this, 
			("You are not logged into the SyrupManager"
			 + "\nYou must login before you can post messages."),
			"Not Logged In!",
			JOptionPane.PLAIN_MESSAGE); 
      }

  }//GEN-LAST:event_postMessageButtonActionPerformed

  private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
	//logout from SyrupManager

	if (loggedIn == true) {
		//Invoke SyrupManager's Logout Operation
		manager.Logout(userid);
		loggedIn = false;
		userid = "default_user";
		syrupScreenName.setEditable(true);
		statusLabel.setText("Not Connected");
        	statusLabel.setForeground(java.awt.Color.red);
		syrupUsersBox.removeAllItems();
	}
	else {
			JOptionPane.showMessageDialog(this, 
				"You are not logged into the SyrupManager",
				"Not Logged In!",
				JOptionPane.PLAIN_MESSAGE); 
	}

  }//GEN-LAST:event_logoutButtonActionPerformed

  private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
	//Login to SyrupManager
      if(loggedIn == false) {
	if((syrupScreenName.getText()).equals("")) {
			JOptionPane.showMessageDialog(this, 
				"Please enter a ScreeName",
				"Enter a Screen Name!",
				JOptionPane.PLAIN_MESSAGE); 
	} 
        else {
		
		userid = syrupScreenName.getText();
		//Invoke SyrupManager's Login Operation
		manager.Login(userid, client);
		loggedIn = true;
		statusLabel.setText("CONNECTED to SYRUP");
        	statusLabel.setForeground(java.awt.Color.green);
		syrupScreenName.setEditable(false);
	}
      }
      else  {
		JOptionPane.showMessageDialog(this, 
			("You are already logged in as: " + userid
                         + "\nPlease logout before attempting to login"),
			"Already Logged in!",
			JOptionPane.PLAIN_MESSAGE); 

      }


  }//GEN-LAST:event_loginButtonActionPerformed

static public void main (String argv[]) {
    final JApplet applet = new SyrupApplet();
    System.runFinalizersOnExit(true);
    Frame frame = new Frame (
                 "SyrupApplet");
    frame.addWindowListener (
                  new WindowAdapter()
    {
      public void windowClosing (
                   WindowEvent event)
      {
        applet.stop();
        applet.destroy();
        System.exit(0);
      }
    });
    frame.add (
      "Center", applet);
    applet.setStub (new MyAppletStub (
         argv, applet));
    frame.pack();
    applet.init();
    applet.start();
    frame.setSize(new Dimension(640,480));
    frame.show();
  }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane syrupTabbedPane;
    private javax.swing.JPanel connectStatusPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField syrupScreenName;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JTextArea postMessageArea;
    private javax.swing.JScrollPane sp0;
    private javax.swing.JButton postMessageButton;
    private javax.swing.JPanel chatPanel;
    private javax.swing.JComboBox syrupUsersBox;
    private javax.swing.JScrollPane sp1;
    private javax.swing.JTextArea messagesFromUsersArea;
    private javax.swing.JTextArea messagesToUserArea;
    private javax.swing.JScrollPane sp2;
    private javax.swing.JScrollPane sp3;
    private javax.swing.JButton sendMessageToUserButton;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

}
