/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "account.h"

#if ( (TC_IMPL_TC_Account_0 == 'a') \
&& (TC_IMPL_TC_Account_1 == 'c') \
&& (TC_IMPL_TC_Account_2 == 'c') \
&& (TC_IMPL_TC_Account_3 == 'o') \
&& (TC_IMPL_TC_Account_4 == 'u') \
&& (TC_IMPL_TC_Account_5 == 'n') \
&& (TC_IMPL_TC_Account_6 == 't') \
) && !defined(TC_DEF_TC_Account)
#define TC_DEF_TC_Account 1
const struct CORBA_TypeCode_struct TC_Account_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Account", "IDL:Account:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long Account__classid = 0;
