
/**
* Account.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from account.idl
* Wednesday, February 28, 2001 10:36:48 AM EST
*/

public interface Account extends AccountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Account
