
/**
* _passlongImplBase.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from passlong.idl
* Monday, February 5, 2001 1:59:07 PM EST
*/

public abstract class _passlongImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements passlong, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _passlongImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("foo", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get (method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // passlong/foo
       {
         int x = in.read_long ();
         int __result = (int)0;
         __result = this.foo (x);
         out = rh.createReply();
         out.write_long (__result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:passlong:1.0"};

  public String[] _ids ()
  {
    return __ids;
  }


} // class _passlongImplBase
