
/**
* passlongOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from passlong.idl
* Monday, February 5, 2001 1:59:07 PM EST
*/

public interface passlongOperations 
{
  int foo (int x);
} // interface passlongOperations
