
/**
* passlong.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from passlong.idl
* Monday, February 5, 2001 1:59:07 PM EST
*/

public interface passlong extends passlongOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface passlong
