
/**
* passlongHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from passlong.idl
* Monday, February 5, 2001 1:59:07 PM EST
*/

public final class passlongHolder implements org.omg.CORBA.portable.Streamable
{
  public passlong value = null;

  public passlongHolder ()
  {
  }

  public passlongHolder (passlong initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = passlongHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    passlongHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return passlongHelper.type ();
  }

}
