
/**
* AccountOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from account.idl
* Tuesday, February 27, 2001 5:40:15 PM EST
*/

public interface AccountOperations 
{
  void deposit (int amount);
  void withdraw (int amount);
  int balance ();
} // interface AccountOperations
