
/**
* AccountHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from account.idl
* Thursday, March 1, 2001 1:11:27 AM EST
*/

public final class AccountHolder implements org.omg.CORBA.portable.Streamable
{
  public Account value = null;

  public AccountHolder ()
  {
  }

  public AccountHolder (Account initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AccountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AccountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AccountHelper.type ();
  }

}
