
/**
* AccountOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from account.idl
* Thursday, March 1, 2001 1:11:27 AM EST
*/

public interface AccountOperations 
{
  void deposit (int amount);
  void withdraw (int amount);
  int balance ();
} // interface AccountOperations
