package Syrup;


/**
* Syrup/_SyrupClientImplBase.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from Syrup.idl
* Thursday, March 8, 2001 2:19:45 AM EST
*/

public abstract class _SyrupClientImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Syrup.SyrupClient, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _SyrupClientImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("Message", new java.lang.Integer (0));
    _methods.put ("AddUserToList", new java.lang.Integer (1));
    _methods.put ("RemoveUserFromList", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get (method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Syrup/SyrupClient/Message
       {
         String userid = in.read_string ();
         String msg = in.read_string ();
         this.Message (userid, msg);
         out = rh.createReply();
         break;
       }

       case 1:  // Syrup/SyrupClient/AddUserToList
       {
         String id = in.read_string ();
         this.AddUserToList (id);
         out = rh.createReply();
         break;
       }

       case 2:  // Syrup/SyrupClient/RemoveUserFromList
       {
         String id = in.read_string ();
         this.RemoveUserFromList (id);
         out = rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Syrup/SyrupClient:1.0"};

  public String[] _ids ()
  {
    return __ids;
  }


} // class _SyrupClientImplBase
