package Syrup;

/**
* Syrup/SyrupClientHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from Syrup.idl
* Thursday, March 8, 2001 2:19:45 AM EST
*/

public final class SyrupClientHolder implements org.omg.CORBA.portable.Streamable
{
  public Syrup.SyrupClient value = null;

  public SyrupClientHolder ()
  {
  }

  public SyrupClientHolder (Syrup.SyrupClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Syrup.SyrupClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Syrup.SyrupClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Syrup.SyrupClientHelper.type ();
  }

}
