package Syrup;


/**
* Syrup/SyrupClientOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from Syrup.idl
* Thursday, March 8, 2001 2:19:45 AM EST
*/

public interface SyrupClientOperations 
{
  void Message (String userid, String msg);
  void AddUserToList (String id);
  void RemoveUserFromList (String id);
} // interface SyrupClientOperations
