package Syrup;


/**
* Syrup/SyrupManagerOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from Syrup.idl
* Thursday, March 8, 2001 2:19:45 AM EST
*/

public interface SyrupManagerOperations 
{
  void Login (String userid, Syrup.SyrupClient client);
  void Logout (String userid);
  void PostMessage (String userid, String msg);
  void SendMessage (String from, String to, String msg);
} // interface SyrupManagerOperations
