package Syrup;


/**
* Syrup/SyrupManagerHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from Syrup.idl
* Thursday, March 8, 2001 2:19:45 AM EST
*/

abstract public class SyrupManagerHelper
{
  private static String  _id = "IDL:Syrup/SyrupManager:1.0";

  public static void insert (org.omg.CORBA.Any a, Syrup.SyrupManager that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Syrup.SyrupManager extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Syrup.SyrupManagerHelper.id (), "SyrupManager");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Syrup.SyrupManager read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SyrupManagerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Syrup.SyrupManager value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Syrup.SyrupManager narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Syrup.SyrupManager)
      return (Syrup.SyrupManager)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      return new Syrup._SyrupManagerStub (delegate);
    }
  }

}
