package Syrup;


/**
* Syrup/SyrupClient.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from Syrup.idl
* Thursday, March 8, 2001 2:19:45 AM EST
*/

public interface SyrupClient extends SyrupClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SyrupClient
