/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "account.h"

void
_ORBIT_skel_Account_deposit(POA_Account * _ORBIT_servant,
			    GIOPRecvBuffer * _ORBIT_recv_buffer,
			    CORBA_Environment * ev,
			    void (*_impl_deposit) (PortableServer_Servant
						   _servant,
						   const CORBA_unsigned_long
						   amount,
						   CORBA_Environment * ev))
{
   CORBA_unsigned_long amount;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (amount))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));} else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 amount = *((CORBA_unsigned_long *) _ORBIT_curptr);
      }
   }
   _impl_deposit(_ORBIT_servant, amount, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Account_withdraw(POA_Account * _ORBIT_servant,
			     GIOPRecvBuffer * _ORBIT_recv_buffer,
			     CORBA_Environment * ev,
			     void (*_impl_withdraw) (PortableServer_Servant
						     _servant,
						     const CORBA_unsigned_long
						     amount,
						     CORBA_Environment * ev))
{
   CORBA_unsigned_long amount;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (amount))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));} else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 amount = *((CORBA_unsigned_long *) _ORBIT_curptr);
      }
   }
   _impl_withdraw(_ORBIT_servant, amount, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Account__get_balance(POA_Account * _ORBIT_servant,
				 GIOPRecvBuffer * _ORBIT_recv_buffer,
				 CORBA_Environment * ev,
				 CORBA_long(*_impl__get_balance)
				 (PortableServer_Servant _servant,
				  CORBA_Environment * ev))
{
   CORBA_long _ORBIT_retval;

   _ORBIT_retval = _impl__get_balance(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_retval));
	       memcpy(_ORBIT_t, &(_ORBIT_retval), sizeof(_ORBIT_retval));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_retval));
	    }
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
static ORBitSkeleton
get_skel_Account(POA_Account * servant,
		 GIOPRecvBuffer * _ORBIT_recv_buffer, gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case '_':
      if (strcmp((opname + 1), "get_balance"))
	 break;
      *impl = (gpointer) servant->vepv->Account_epv->_get_balance;
      return (ORBitSkeleton) _ORBIT_skel_Account__get_balance;
      break;
     case 'd':
      if (strcmp((opname + 1), "eposit"))
	 break;
      *impl = (gpointer) servant->vepv->Account_epv->deposit;
      return (ORBitSkeleton) _ORBIT_skel_Account_deposit;
      break;
     case 'w':
      if (strcmp((opname + 1), "ithdraw"))
	 break;
      *impl = (gpointer) servant->vepv->Account_epv->withdraw;
      return (ORBitSkeleton) _ORBIT_skel_Account_withdraw;
      break;
     default:
      break;
   }
   return NULL;
}

static void
init_local_objref_Account(CORBA_Object obj, POA_Account * servant)
{
   obj->vepv[Account__classid] = servant->vepv->Account_epv;
}
void
POA_Account__init(PortableServer_Servant servant, CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_Account, "IDL:Account:1.0",
	 (ORBit_local_objref_init) & init_local_objref_Account };

   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!Account__classid)
      Account__classid = ORBit_register_class(&class_info);
}

void
POA_Account__fini(PortableServer_Servant servant, CORBA_Environment * env)
{
   PortableServer_ServantBase__fini(servant, env);
}
