/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "CosNaming.h"

#if ( (TC_IMPL_TC_CosNaming_Istring_0 == 'C') \
&& (TC_IMPL_TC_CosNaming_Istring_1 == 'o') \
&& (TC_IMPL_TC_CosNaming_Istring_2 == 's') \
&& (TC_IMPL_TC_CosNaming_Istring_3 == 'N') \
&& (TC_IMPL_TC_CosNaming_Istring_4 == 'a') \
&& (TC_IMPL_TC_CosNaming_Istring_5 == 'm') \
&& (TC_IMPL_TC_CosNaming_Istring_6 == 'i') \
&& (TC_IMPL_TC_CosNaming_Istring_7 == 'n') \
&& (TC_IMPL_TC_CosNaming_Istring_8 == 'g') \
) && !defined(TC_DEF_TC_CosNaming_Istring)
#define TC_DEF_TC_CosNaming_Istring 1
static const CORBA_TypeCode anon_subtypes_array7[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_CosNaming_Istring_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "Istring", "IDL:omg.org/CosNaming/Istring:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array7,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CosNaming_NameComponent_0 == 'C') \
&& (TC_IMPL_TC_CosNaming_NameComponent_1 == 'o') \
&& (TC_IMPL_TC_CosNaming_NameComponent_2 == 's') \
&& (TC_IMPL_TC_CosNaming_NameComponent_3 == 'N') \
&& (TC_IMPL_TC_CosNaming_NameComponent_4 == 'a') \
&& (TC_IMPL_TC_CosNaming_NameComponent_5 == 'm') \
&& (TC_IMPL_TC_CosNaming_NameComponent_6 == 'i') \
&& (TC_IMPL_TC_CosNaming_NameComponent_7 == 'n') \
&& (TC_IMPL_TC_CosNaming_NameComponent_8 == 'g') \
) && !defined(TC_DEF_TC_CosNaming_NameComponent)
#define TC_DEF_TC_CosNaming_NameComponent 1
static const char *anon_subnames_array10[] = { "id", "kind" };
static const CORBA_TypeCode anon_subtypes_array11[] =
   { (CORBA_TypeCode) & TC_CosNaming_Istring_struct,
      (CORBA_TypeCode) & TC_CosNaming_Istring_struct };
const struct CORBA_TypeCode_struct TC_CosNaming_NameComponent_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_struct, "NameComponent",
      "IDL:omg.org/CosNaming/NameComponent:1.0",

   0, 2,
   (const char **) anon_subnames_array10,
   (CORBA_TypeCode *) anon_subtypes_array11,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_0 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_2 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_3 == 'N') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_5 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_6 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_7 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_8 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_CosNaming_NameComponent)
#define TC_DEF_TC_CORBA_sequence_CosNaming_NameComponent 1
static const CORBA_TypeCode anon_subtypes_array15[] =
   { (CORBA_TypeCode) & TC_CosNaming_NameComponent_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_CosNaming_NameComponent_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array15,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_0 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_2 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_3 == 'N') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_5 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_6 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_7 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_NameComponent_8 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_CosNaming_NameComponent)
#define TC_DEF_TC_CORBA_sequence_CosNaming_NameComponent 1
static const CORBA_TypeCode anon_subtypes_array24[] =
   { (CORBA_TypeCode) & TC_CosNaming_NameComponent_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_CosNaming_NameComponent_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array24,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CosNaming_Name_0 == 'C') \
&& (TC_IMPL_TC_CosNaming_Name_1 == 'o') \
&& (TC_IMPL_TC_CosNaming_Name_2 == 's') \
&& (TC_IMPL_TC_CosNaming_Name_3 == 'N') \
&& (TC_IMPL_TC_CosNaming_Name_4 == 'a') \
&& (TC_IMPL_TC_CosNaming_Name_5 == 'm') \
&& (TC_IMPL_TC_CosNaming_Name_6 == 'i') \
&& (TC_IMPL_TC_CosNaming_Name_7 == 'n') \
&& (TC_IMPL_TC_CosNaming_Name_8 == 'g') \
) && !defined(TC_DEF_TC_CosNaming_Name)
#define TC_DEF_TC_CosNaming_Name 1
static const CORBA_TypeCode anon_subtypes_array28[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CosNaming_NameComponent_struct };
const struct CORBA_TypeCode_struct TC_CosNaming_Name_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "Name", "IDL:omg.org/CosNaming/Name:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array28,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CosNaming_BindingType_0 == 'C') \
&& (TC_IMPL_TC_CosNaming_BindingType_1 == 'o') \
&& (TC_IMPL_TC_CosNaming_BindingType_2 == 's') \
&& (TC_IMPL_TC_CosNaming_BindingType_3 == 'N') \
&& (TC_IMPL_TC_CosNaming_BindingType_4 == 'a') \
&& (TC_IMPL_TC_CosNaming_BindingType_5 == 'm') \
&& (TC_IMPL_TC_CosNaming_BindingType_6 == 'i') \
&& (TC_IMPL_TC_CosNaming_BindingType_7 == 'n') \
&& (TC_IMPL_TC_CosNaming_BindingType_8 == 'g') \
) && !defined(TC_DEF_TC_CosNaming_BindingType)
#define TC_DEF_TC_CosNaming_BindingType 1
static const char *anon_subnames_array31[] = { "nobject", "ncontext" };
const struct CORBA_TypeCode_struct TC_CosNaming_BindingType_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_enum, "BindingType", "IDL:omg.org/CosNaming/BindingType:1.0",
   0, 2,
   (const char **) anon_subnames_array31,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CosNaming_Binding_0 == 'C') \
&& (TC_IMPL_TC_CosNaming_Binding_1 == 'o') \
&& (TC_IMPL_TC_CosNaming_Binding_2 == 's') \
&& (TC_IMPL_TC_CosNaming_Binding_3 == 'N') \
&& (TC_IMPL_TC_CosNaming_Binding_4 == 'a') \
&& (TC_IMPL_TC_CosNaming_Binding_5 == 'm') \
&& (TC_IMPL_TC_CosNaming_Binding_6 == 'i') \
&& (TC_IMPL_TC_CosNaming_Binding_7 == 'n') \
&& (TC_IMPL_TC_CosNaming_Binding_8 == 'g') \
) && !defined(TC_DEF_TC_CosNaming_Binding)
#define TC_DEF_TC_CosNaming_Binding 1
static const char *anon_subnames_array35[] =

   { "binding_name", "binding_type" };
static const CORBA_TypeCode anon_subtypes_array36[] =
   { (CORBA_TypeCode) & TC_CosNaming_Name_struct,
      (CORBA_TypeCode) & TC_CosNaming_BindingType_struct };
const struct CORBA_TypeCode_struct TC_CosNaming_Binding_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_struct, "Binding", "IDL:omg.org/CosNaming/Binding:1.0",
   0, 2,
   (const char **) anon_subnames_array35,
   (CORBA_TypeCode *) anon_subtypes_array36,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_0 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_2 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_3 == 'N') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_5 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_6 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_7 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_8 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_CosNaming_Binding)
#define TC_DEF_TC_CORBA_sequence_CosNaming_Binding 1
static const CORBA_TypeCode anon_subtypes_array40[] =
   { (CORBA_TypeCode) & TC_CosNaming_Binding_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CosNaming_Binding_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array40,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_0 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_2 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_3 == 'N') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_5 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_6 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_7 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CosNaming_Binding_8 == 'g') \
) && !defined(TC_DEF_TC_CORBA_sequence_CosNaming_Binding)
#define TC_DEF_TC_CORBA_sequence_CosNaming_Binding 1
static const CORBA_TypeCode anon_subtypes_array49[] =
   { (CORBA_TypeCode) & TC_CosNaming_Binding_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CosNaming_Binding_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array49,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CosNaming_BindingList_0 == 'C') \
&& (TC_IMPL_TC_CosNaming_BindingList_1 == 'o') \
&& (TC_IMPL_TC_CosNaming_BindingList_2 == 's') \
&& (TC_IMPL_TC_CosNaming_BindingList_3 == 'N') \
&& (TC_IMPL_TC_CosNaming_BindingList_4 == 'a') \
&& (TC_IMPL_TC_CosNaming_BindingList_5 == 'm') \
&& (TC_IMPL_TC_CosNaming_BindingList_6 == 'i') \
&& (TC_IMPL_TC_CosNaming_BindingList_7 == 'n') \
&& (TC_IMPL_TC_CosNaming_BindingList_8 == 'g') \
) && !defined(TC_DEF_TC_CosNaming_BindingList)
#define TC_DEF_TC_CosNaming_BindingList 1
static const CORBA_TypeCode anon_subtypes_array53[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CosNaming_Binding_struct };
const struct CORBA_TypeCode_struct TC_CosNaming_BindingList_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "BindingList", "IDL:omg.org/CosNaming/BindingList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array53,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CosNaming_NamingContext_0 == 'C') \
&& (TC_IMPL_TC_CosNaming_NamingContext_1 == 'o') \
&& (TC_IMPL_TC_CosNaming_NamingContext_2 == 's') \
&& (TC_IMPL_TC_CosNaming_NamingContext_3 == 'N') \
&& (TC_IMPL_TC_CosNaming_NamingContext_4 == 'a') \
&& (TC_IMPL_TC_CosNaming_NamingContext_5 == 'm') \
&& (TC_IMPL_TC_CosNaming_NamingContext_6 == 'i') \
&& (TC_IMPL_TC_CosNaming_NamingContext_7 == 'n') \
&& (TC_IMPL_TC_CosNaming_NamingContext_8 == 'g') \
) && !defined(TC_DEF_TC_CosNaming_NamingContext)
#define TC_DEF_TC_CosNaming_NamingContext 1
const struct CORBA_TypeCode_struct TC_CosNaming_NamingContext_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "NamingContext",
      "IDL:omg.org/CosNaming/NamingContext:1.0",

   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CosNaming_NamingContext_NotFoundReason_0 == 'C') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFoundReason_1 == 'o') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFoundReason_2 == 's') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFoundReason_3 == 'N') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFoundReason_4 == 'a') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFoundReason_5 == 'm') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFoundReason_6 == 'i') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFoundReason_7 == 'n') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFoundReason_8 == 'g') \
) && !defined(TC_DEF_TC_CosNaming_NamingContext_NotFoundReason)
#define TC_DEF_TC_CosNaming_NamingContext_NotFoundReason 1
static const char *anon_subnames_array60[] =
   { "missing_node", "not_context", "not_object" };
const struct CORBA_TypeCode_struct
   TC_CosNaming_NamingContext_NotFoundReason_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_enum, "NotFoundReason",
      "IDL:omg.org/CosNaming/NamingContext/NotFoundReason:1.0",
   0, 3,
   (const char **) anon_subnames_array60,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CosNaming_NamingContext_NotFound_0 == 'C') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFound_1 == 'o') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFound_2 == 's') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFound_3 == 'N') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFound_4 == 'a') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFound_5 == 'm') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFound_6 == 'i') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFound_7 == 'n') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotFound_8 == 'g') \
) && !defined(TC_DEF_TC_CosNaming_NamingContext_NotFound)
#define TC_DEF_TC_CosNaming_NamingContext_NotFound 1
static const char *anon_subnames_array64[] = { "why", "rest_of_name" };
static const CORBA_TypeCode anon_subtypes_array65[] =
   { (CORBA_TypeCode) & TC_CosNaming_NamingContext_NotFoundReason_struct,
      (CORBA_TypeCode) & TC_CosNaming_Name_struct };
const struct CORBA_TypeCode_struct TC_CosNaming_NamingContext_NotFound_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "NotFound",
      "IDL:omg.org/CosNaming/NamingContext/NotFound:1.0",
   0, 2,
   (const char **) anon_subnames_array64,
   (CORBA_TypeCode *) anon_subtypes_array65,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CosNaming_NamingContext_CannotProceed_0 == 'C') \
&& (TC_IMPL_TC_CosNaming_NamingContext_CannotProceed_1 == 'o') \
&& (TC_IMPL_TC_CosNaming_NamingContext_CannotProceed_2 == 's') \
&& (TC_IMPL_TC_CosNaming_NamingContext_CannotProceed_3 == 'N') \
&& (TC_IMPL_TC_CosNaming_NamingContext_CannotProceed_4 == 'a') \
&& (TC_IMPL_TC_CosNaming_NamingContext_CannotProceed_5 == 'm') \
&& (TC_IMPL_TC_CosNaming_NamingContext_CannotProceed_6 == 'i') \
&& (TC_IMPL_TC_CosNaming_NamingContext_CannotProceed_7 == 'n') \
&& (TC_IMPL_TC_CosNaming_NamingContext_CannotProceed_8 == 'g') \
) && !defined(TC_DEF_TC_CosNaming_NamingContext_CannotProceed)
#define TC_DEF_TC_CosNaming_NamingContext_CannotProceed 1
static const char *anon_subnames_array68[] = { "ctx", "rest_of_name" };
static const CORBA_TypeCode anon_subtypes_array69[] =
   { (CORBA_TypeCode) & TC_Object_struct,
      (CORBA_TypeCode) & TC_CosNaming_Name_struct };
const struct CORBA_TypeCode_struct
   TC_CosNaming_NamingContext_CannotProceed_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "CannotProceed",
      "IDL:omg.org/CosNaming/NamingContext/CannotProceed:1.0",
   0, 2,
   (const char **) anon_subnames_array68,
   (CORBA_TypeCode *) anon_subtypes_array69,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CosNaming_NamingContext_InvalidName_0 == 'C') \
&& (TC_IMPL_TC_CosNaming_NamingContext_InvalidName_1 == 'o') \
&& (TC_IMPL_TC_CosNaming_NamingContext_InvalidName_2 == 's') \
&& (TC_IMPL_TC_CosNaming_NamingContext_InvalidName_3 == 'N') \
&& (TC_IMPL_TC_CosNaming_NamingContext_InvalidName_4 == 'a') \
&& (TC_IMPL_TC_CosNaming_NamingContext_InvalidName_5 == 'm') \
&& (TC_IMPL_TC_CosNaming_NamingContext_InvalidName_6 == 'i') \
&& (TC_IMPL_TC_CosNaming_NamingContext_InvalidName_7 == 'n') \
&& (TC_IMPL_TC_CosNaming_NamingContext_InvalidName_8 == 'g') \
) && !defined(TC_DEF_TC_CosNaming_NamingContext_InvalidName)
#define TC_DEF_TC_CosNaming_NamingContext_InvalidName 1
const struct CORBA_TypeCode_struct
   TC_CosNaming_NamingContext_InvalidName_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "InvalidName",
      "IDL:omg.org/CosNaming/NamingContext/InvalidName:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CosNaming_NamingContext_AlreadyBound_0 == 'C') \
&& (TC_IMPL_TC_CosNaming_NamingContext_AlreadyBound_1 == 'o') \
&& (TC_IMPL_TC_CosNaming_NamingContext_AlreadyBound_2 == 's') \
&& (TC_IMPL_TC_CosNaming_NamingContext_AlreadyBound_3 == 'N') \
&& (TC_IMPL_TC_CosNaming_NamingContext_AlreadyBound_4 == 'a') \
&& (TC_IMPL_TC_CosNaming_NamingContext_AlreadyBound_5 == 'm') \
&& (TC_IMPL_TC_CosNaming_NamingContext_AlreadyBound_6 == 'i') \
&& (TC_IMPL_TC_CosNaming_NamingContext_AlreadyBound_7 == 'n') \
&& (TC_IMPL_TC_CosNaming_NamingContext_AlreadyBound_8 == 'g') \
) && !defined(TC_DEF_TC_CosNaming_NamingContext_AlreadyBound)
#define TC_DEF_TC_CosNaming_NamingContext_AlreadyBound 1
const struct CORBA_TypeCode_struct
   TC_CosNaming_NamingContext_AlreadyBound_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "AlreadyBound",
      "IDL:omg.org/CosNaming/NamingContext/AlreadyBound:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CosNaming_NamingContext_NotEmpty_0 == 'C') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotEmpty_1 == 'o') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotEmpty_2 == 's') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotEmpty_3 == 'N') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotEmpty_4 == 'a') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotEmpty_5 == 'm') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotEmpty_6 == 'i') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotEmpty_7 == 'n') \
&& (TC_IMPL_TC_CosNaming_NamingContext_NotEmpty_8 == 'g') \
) && !defined(TC_DEF_TC_CosNaming_NamingContext_NotEmpty)
#define TC_DEF_TC_CosNaming_NamingContext_NotEmpty 1
const struct CORBA_TypeCode_struct TC_CosNaming_NamingContext_NotEmpty_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "NotEmpty",
      "IDL:omg.org/CosNaming/NamingContext/NotEmpty:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CosNaming_BindingIterator_0 == 'C') \
&& (TC_IMPL_TC_CosNaming_BindingIterator_1 == 'o') \
&& (TC_IMPL_TC_CosNaming_BindingIterator_2 == 's') \
&& (TC_IMPL_TC_CosNaming_BindingIterator_3 == 'N') \
&& (TC_IMPL_TC_CosNaming_BindingIterator_4 == 'a') \
&& (TC_IMPL_TC_CosNaming_BindingIterator_5 == 'm') \
&& (TC_IMPL_TC_CosNaming_BindingIterator_6 == 'i') \
&& (TC_IMPL_TC_CosNaming_BindingIterator_7 == 'n') \
&& (TC_IMPL_TC_CosNaming_BindingIterator_8 == 'g') \
) && !defined(TC_DEF_TC_CosNaming_BindingIterator)
#define TC_DEF_TC_CosNaming_BindingIterator 1
const struct CORBA_TypeCode_struct TC_CosNaming_BindingIterator_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "BindingIterator",
      "IDL:omg.org/CosNaming/BindingIterator:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
gpointer
CosNaming_NameComponent__free(gpointer mem, gpointer dat,
			      CORBA_boolean free_strings)
{
   CosNaming_NameComponent *var = mem;

   if (free_strings) {
      CosNaming_Istring__free(&(var->id), NULL, free_strings);
   }
   if (free_strings) {
      CosNaming_Istring__free(&(var->kind), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

CosNaming_NameComponent *
CosNaming_NameComponent__alloc(void)
{
   CosNaming_NameComponent *retval;

   retval =
      ORBit_alloc(sizeof(CosNaming_NameComponent),
		  (ORBit_free_childvals) CosNaming_NameComponent__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->id), '\0', sizeof(retval->id));
   memset(&(retval->kind), '\0', sizeof(retval->kind));
   return retval;
}

#if ( (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_0 == 'C') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_1 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_2 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_3 == 'N') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_4 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_5 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_6 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_7 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_8 == 'g') \
) && !defined(ORBIT_DEF_CORBA_sequence_CosNaming_NameComponent)
#define ORBIT_DEF_CORBA_sequence_CosNaming_NameComponent 1

gpointer
CORBA_sequence_CosNaming_NameComponent__free(gpointer mem, gpointer dat,
					     CORBA_boolean free_strings)
{
   CORBA_sequence_CosNaming_NameComponent *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CosNaming_NameComponent *
CORBA_sequence_CosNaming_NameComponent__alloc(void)
{
   CORBA_sequence_CosNaming_NameComponent *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CosNaming_NameComponent),
		  (ORBit_free_childvals)
		  CORBA_sequence_CosNaming_NameComponent__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CosNaming_NameComponent *
CORBA_sequence_CosNaming_NameComponent_allocbuf(CORBA_unsigned_long len)
{
   CosNaming_NameComponent *retval =
      ORBit_alloc(sizeof(CosNaming_NameComponent) * len,
		  (ORBit_free_childvals) CosNaming_NameComponent__free,
		  GUINT_TO_POINTER(len));

   memset(retval, '\0', sizeof(CosNaming_NameComponent) * len);
   return retval;
}
#endif

gpointer
CosNaming_Name__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   return CORBA_sequence_CosNaming_NameComponent__free(mem, dat,
						       free_strings);
}

CosNaming_Name *
CosNaming_Name__alloc(void)
{
   return CORBA_sequence_CosNaming_NameComponent__alloc();
}

#if ( (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_0 == 'C') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_1 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_2 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_3 == 'N') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_4 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_5 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_6 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_7 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_8 == 'g') \
) && !defined(ORBIT_DEF_CORBA_sequence_CosNaming_NameComponent)
#define ORBIT_DEF_CORBA_sequence_CosNaming_NameComponent 1

gpointer
CORBA_sequence_CosNaming_NameComponent__free(gpointer mem, gpointer dat,
					     CORBA_boolean free_strings)
{
   CORBA_sequence_CosNaming_NameComponent *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CosNaming_NameComponent *
CORBA_sequence_CosNaming_NameComponent__alloc(void)
{
   CORBA_sequence_CosNaming_NameComponent *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CosNaming_NameComponent),
		  (ORBit_free_childvals)
		  CORBA_sequence_CosNaming_NameComponent__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CosNaming_NameComponent *
CORBA_sequence_CosNaming_NameComponent_allocbuf(CORBA_unsigned_long len)
{
   CosNaming_NameComponent *retval =
      ORBit_alloc(sizeof(CosNaming_NameComponent) * len,
		  (ORBit_free_childvals) CosNaming_NameComponent__free,
		  GUINT_TO_POINTER(len));

   memset(retval, '\0', sizeof(CosNaming_NameComponent) * len);
   return retval;
}
#endif

gpointer
CosNaming_Binding__free(gpointer mem, gpointer dat,
			CORBA_boolean free_strings)
{
   CosNaming_Binding *var = mem;

   {
      CosNaming_Name__free(&(var->binding_name), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

CosNaming_Binding *
CosNaming_Binding__alloc(void)
{
   CosNaming_Binding *retval;

   retval =
      ORBit_alloc(sizeof(CosNaming_Binding),
		  (ORBit_free_childvals) CosNaming_Binding__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->binding_name), '\0', sizeof(retval->binding_name));
   return retval;
}

#if ( (ORBIT_IMPL_CORBA_sequence_CosNaming_Binding_0 == 'C') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_Binding_1 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_Binding_2 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_Binding_3 == 'N') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_Binding_4 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_Binding_5 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_Binding_6 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_Binding_7 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_Binding_8 == 'g') \
) && !defined(ORBIT_DEF_CORBA_sequence_CosNaming_Binding)
#define ORBIT_DEF_CORBA_sequence_CosNaming_Binding 1

gpointer
CORBA_sequence_CosNaming_Binding__free(gpointer mem, gpointer dat,
				       CORBA_boolean free_strings)
{
   CORBA_sequence_CosNaming_Binding *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CosNaming_Binding *
CORBA_sequence_CosNaming_Binding__alloc(void)
{
   CORBA_sequence_CosNaming_Binding *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CosNaming_Binding),
		  (ORBit_free_childvals)
		  CORBA_sequence_CosNaming_Binding__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CosNaming_Binding *
CORBA_sequence_CosNaming_Binding_allocbuf(CORBA_unsigned_long len)
{
   CosNaming_Binding *retval =
      ORBit_alloc(sizeof(CosNaming_Binding) * len,
		  (ORBit_free_childvals) CosNaming_Binding__free,
		  GUINT_TO_POINTER(len));

   memset(retval, '\0', sizeof(CosNaming_Binding) * len);
   return retval;
}
#endif

gpointer
CosNaming_BindingList__free(gpointer mem, gpointer dat,
			    CORBA_boolean free_strings)
{
   return CORBA_sequence_CosNaming_Binding__free(mem, dat, free_strings);
}

CosNaming_BindingList *
CosNaming_BindingList__alloc(void)
{
   return CORBA_sequence_CosNaming_Binding__alloc();
}

#if ( (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_0 == 'C') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_1 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_2 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_3 == 'N') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_4 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_5 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_6 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_7 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_8 == 'g') \
) && !defined(ORBIT_DEF_CORBA_sequence_CosNaming_NameComponent)
#define ORBIT_DEF_CORBA_sequence_CosNaming_NameComponent 1

gpointer
CORBA_sequence_CosNaming_NameComponent__free(gpointer mem, gpointer dat,
					     CORBA_boolean free_strings)
{
   CORBA_sequence_CosNaming_NameComponent *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CosNaming_NameComponent *
CORBA_sequence_CosNaming_NameComponent__alloc(void)
{
   CORBA_sequence_CosNaming_NameComponent *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CosNaming_NameComponent),
		  (ORBit_free_childvals)
		  CORBA_sequence_CosNaming_NameComponent__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CosNaming_NameComponent *
CORBA_sequence_CosNaming_NameComponent_allocbuf(CORBA_unsigned_long len)
{
   CosNaming_NameComponent *retval =
      ORBit_alloc(sizeof(CosNaming_NameComponent) * len,
		  (ORBit_free_childvals) CosNaming_NameComponent__free,
		  GUINT_TO_POINTER(len));

   memset(retval, '\0', sizeof(CosNaming_NameComponent) * len);
   return retval;
}
#endif

gpointer
CosNaming_NamingContext_NotFound__free(gpointer mem, gpointer dat,
				       CORBA_boolean free_strings)
{
   CosNaming_NamingContext_NotFound *var = mem;

   {
      CosNaming_Name__free(&(var->rest_of_name), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

CosNaming_NamingContext_NotFound *
CosNaming_NamingContext_NotFound__alloc(void)
{
   CosNaming_NamingContext_NotFound *retval;

   retval =
      ORBit_alloc(sizeof(CosNaming_NamingContext_NotFound),
		  (ORBit_free_childvals)
		  CosNaming_NamingContext_NotFound__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->rest_of_name), '\0', sizeof(retval->rest_of_name));
   return retval;
}

#if ( (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_0 == 'C') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_1 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_2 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_3 == 'N') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_4 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_5 == 'm') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_6 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_7 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CosNaming_NameComponent_8 == 'g') \
) && !defined(ORBIT_DEF_CORBA_sequence_CosNaming_NameComponent)
#define ORBIT_DEF_CORBA_sequence_CosNaming_NameComponent 1

gpointer
CORBA_sequence_CosNaming_NameComponent__free(gpointer mem, gpointer dat,
					     CORBA_boolean free_strings)
{
   CORBA_sequence_CosNaming_NameComponent *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CosNaming_NameComponent *
CORBA_sequence_CosNaming_NameComponent__alloc(void)
{
   CORBA_sequence_CosNaming_NameComponent *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CosNaming_NameComponent),
		  (ORBit_free_childvals)
		  CORBA_sequence_CosNaming_NameComponent__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CosNaming_NameComponent *
CORBA_sequence_CosNaming_NameComponent_allocbuf(CORBA_unsigned_long len)
{
   CosNaming_NameComponent *retval =
      ORBit_alloc(sizeof(CosNaming_NameComponent) * len,
		  (ORBit_free_childvals) CosNaming_NameComponent__free,
		  GUINT_TO_POINTER(len));

   memset(retval, '\0', sizeof(CosNaming_NameComponent) * len);
   return retval;
}
#endif

gpointer
CosNaming_NamingContext_CannotProceed__free(gpointer mem, gpointer dat,
					    CORBA_boolean free_strings)
{
   CosNaming_NamingContext_CannotProceed *var = mem;

   {
      CosNaming_NamingContext__free(&(var->ctx), NULL, free_strings);
   }
   {
      CosNaming_Name__free(&(var->rest_of_name), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

CosNaming_NamingContext_CannotProceed *
CosNaming_NamingContext_CannotProceed__alloc(void)
{
   CosNaming_NamingContext_CannotProceed *retval;

   retval =
      ORBit_alloc(sizeof(CosNaming_NamingContext_CannotProceed),
		  (ORBit_free_childvals)
		  CosNaming_NamingContext_CannotProceed__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->ctx), '\0', sizeof(retval->ctx));
   memset(&(retval->rest_of_name), '\0', sizeof(retval->rest_of_name));
   return retval;
}

gpointer
CosNaming_NamingContext_InvalidName__free(gpointer mem, gpointer dat,
					  CORBA_boolean free_strings)
{
   CosNaming_NamingContext_InvalidName *var = mem;

   return (gpointer) (var + 1);
}

gpointer
CosNaming_NamingContext_AlreadyBound__free(gpointer mem, gpointer dat,
					   CORBA_boolean free_strings)
{
   CosNaming_NamingContext_AlreadyBound *var = mem;

   return (gpointer) (var + 1);
}

gpointer
CosNaming_NamingContext_NotEmpty__free(gpointer mem, gpointer dat,
				       CORBA_boolean free_strings)
{
   CosNaming_NamingContext_NotEmpty *var = mem;

   return (gpointer) (var + 1);
}

CORBA_unsigned_long CosNaming_NamingContext__classid = 0;
CORBA_unsigned_long CosNaming_BindingIterator__classid = 0;
