/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "factory.h"

#if ( (TC_IMPL_TC_factory_0 == 'f') \
&& (TC_IMPL_TC_factory_1 == 'a') \
&& (TC_IMPL_TC_factory_2 == 'c') \
&& (TC_IMPL_TC_factory_3 == 't') \
&& (TC_IMPL_TC_factory_4 == 'o') \
&& (TC_IMPL_TC_factory_5 == 'r') \
&& (TC_IMPL_TC_factory_6 == 'y') \
) && !defined(TC_DEF_TC_factory)
#define TC_DEF_TC_factory 1
const struct CORBA_TypeCode_struct TC_factory_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "factory", "IDL:factory:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long factory__classid = 0;
